config/routes.rb
Rails.application.routes.draw do

  resources :solicitantes do
    resources :beneficiarios do
      resources :solicitudes
    end
  end
  resources :solicitudes
  resources :ayudas
  resources :departamentos
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beneficiario.rb
class Beneficiario < ApplicationRecord
  has_many :historiales
  has_many :solicitantes, through: :historiales
  has_many :solicitudes, dependent: :destroy

  accepts_nested_attributes_for :historiales

  validates :cedula, :nombres, :apellidos, :tipo_cedula, :sexo, :fecha_de_nacimiento, :oficio, :estado_civil, :tipo_de_casa, :num_habitaciones, :num_banos, presence: true, :allow_blank => false
  validates :cedula, uniqueness: { case_sensitive: false, message: 'Ya se encuentra registrada' }, numericality: { only_integer: true }

  def self.search(search)
     search = search.downcase

      where('cedula = ?', "#{search}").order(:id)

  end
end

app/controllers/beneficiarios_controller.rb
class BeneficiariosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_beneficiario, only: [:show, :edit, :update, :destroy]

  # GET /beneficiarios
  # GET /beneficiarios.json
  def index

  end

  # GET /beneficiarios/1
  # GET /beneficiarios/1.json
  def show
    @solicitante= Solicitante.find(params[:solicitante_id])
    @beneficiario= Beneficiario.find(params[:id])
    @solicitudes = Solicitud.where(solicitante_id: @solicitante.id, beneficiario_id: @beneficiario.id).all
  end

  # GET /beneficiarios/new
  def new
    authorize! :new,Beneficiario
    @solicitante= Solicitante.find(params[:solicitante_id])
    @beneficiario = @solicitante.beneficiarios.new
    respond_to do |format|
      format.html
      format.xml  { render :xml => @beneficiario }
    end
  end

  # GET /beneficiarios/1/edits
  def edit
    authorize! :edit,Beneficiario
    @solicitante= Solicitante.find(params[:solicitante_id])
  end

  # POST /beneficiarios
  # POST /beneficiarios.json
  def create
    authorize! :create,Beneficiario
    solicitante=Solicitante.find(params[:solicitante_id])
    @beneficiario = Beneficiario.create(beneficiario_params)
    @beneficiario.historiales.build(parentesco: beneficiario_params[:parentesco], solicitante_id: solicitante.id)
    respond_to do |format|
      if @beneficiario.save
        format.html { redirect_to solicitante_beneficiario_path(solicitante, @beneficiario), notice: 'Beneficiario creado exitosamente.' }
        format.json { render :show, status: :created, location: solicitante_beneficiario_path(solicitante, @beneficiario) }
      else
        format.html { render :new }
        format.json { render json: @beneficiario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiarios/1
  # PATCH/PUT /beneficiarios/1.json
  def update
    authorize! :update,Beneficiario
    @solicitante= Solicitante.find(params[:solicitante_id])
    @beneficiario = Beneficiario.update(beneficiario_params)

        respond_to do |format|
            format.html { redirect_to solicitante_beneficiario_path(@solicitante, params[:id]), notice: 'Beneficiario actualizado exitosamente.' }
            format.json { render :show, status: :ok, location: solicitante_beneficiario_path(@solicitante, @beneficiario) }

        end
  end

  # DELETE /beneficiarios/1
  # DELETE /beneficiarios/1.json
  def destroy
    authorize! :destroy,Beneficiario
    @beneficiario.destroy
    respond_to do |format|
      format.html { redirect_to beneficiarios_url, notice: 'Beneficiario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiario
      @beneficiario = Beneficiario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiario_params
      params.require(:beneficiario).permit(:tipo_cedula, :cedula, :nombres, :apellidos, :sexo, :fecha_de_nacimiento, :oficio, :estado_civil, :tipo_de_casa, :num_habitaciones, :num_banos, :enseres, :obs_enseres, :discapacidad, :obs_discapacidad, :historiales_attributes => [:parentesco])
    end
end

app/helpers/beneficiarios_helper.rb
module BeneficiariosHelper
end

app/views/beneficiarios/_form.html.erb
<%= simple_form_for([@solicitante, @beneficiario]) do |f| %>


<%= f.error_notification %>
<ul class="list-group ">
  <li class="list-group-item text-muted col-md-12" contenteditable="false"><i class="fa fa-database"></i> Datos<div class="pull-right text-warning">
    <i class="fa fa-asterisk"></i> Campo Obligatorio
      </div></li>
  <li class="list-group-item col-md-12">

    <div class="form-inputs">
      <div class="col-md-4 <%='has-error' if @beneficiario.errors.keys.include?(:cedula) ==true or @beneficiario.errors.keys.include?(:tipo_de_cedula) ==true %> <%='has-success' if ((@beneficiario.errors.keys.include?(:cedula) ==false and @beneficiario.errors.keys.include?(:tipo_de_cedula) ==false) and @beneficiario.errors.any?)%>">
        <div class="form-group">
          <%= f.label :cedula, class: "control-label"%>
          <div class="input-group form-inline">
            <span class="input-group-btn">
              <%= f.select(:tipo_cedula , options_for_select($dic["tipo_de_cedula"],@beneficiario.tipo_cedula),{include_blank: ''}, class: "dropdown-toggle form-control", style: "padding:7px 12px;width:60px", id: "tipo_cedula" ) %>

            </span>
              <%= f.input_field :cedula, id: "cedula", class:"form-control"%>
          </div>
        </div>
      </div>

      <div class="col-md-4 <%='has-error' if @beneficiario.errors.keys.include?(:nombres) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:nombres) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :nombres, :input_html => { :id => "nombre" } %>
      </div>
      <div class="col-md-4 <%='has-error' if @beneficiario.errors.keys.include?(:apellidos) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:apellidos) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :apellidos, :input_html => { :id => "apellido" } %>
      </div>
      <div class="col-md-4 <%='has-error' if @beneficiario.errors.keys.include?(:sexo) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:sexo) ==false and @beneficiario.errors.any?)%>">
        <%= f.label :sexo %>
        <%= f.select(:sexo , options_for_select($dic["sexo"],@beneficiario.sexo),{include_blank: 'Seleccione un sexo...'},class: "form-control", id: "sexo" )  %>
      </div>
      <div class="col-md-2 <%='has-error' if @beneficiario.errors.keys.include?(:fecha_de_nacimiento) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:fecha_de_nacimiento) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :fecha_de_nacimiento, as: :date, html5: true, :input_html => { :id => "fecha" } %>
      </div>
      <div class="col-md-2">
        <%= f.label :oficio %>
        <%= f.select(:oficio , options_for_select($dic["oficio"],@beneficiario.oficio),{include_blank: 'Seleccione un oficio...'},class: "form-control" )  %>
      </div>
      <div class="col-md-4">
        <%= f.label :estado_civil %>
        <%= f.select(:estado_civil , options_for_select($dic["estado"],@beneficiario.estado_civil),{include_blank: 'Seleccione un estado civil...'},class: "form-control" )  %>
      </br>
      </div>
      <div class="col-md-4">
        <%= f.label :tipo_de_casa %>
        <%= f.select(:tipo_de_casa , options_for_select($dic["tipo_de_casa"],@beneficiario.tipo_de_casa),{include_blank: 'Seleccione un tipo de casa...'},class: "form-control" )  %>
      </div>
      <div class="col-md-2 <%='has-error' if @beneficiario.errors.keys.include?(:num_habitaciones) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:num_habitaciones) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :num_habitaciones %>
      </div>
      <div class="col-md-2 <%='has-error' if @beneficiario.errors.keys.include?(:num_banos) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:num_banos) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :num_banos %>
      </div>
      <div class="col-md-1">
        <%= f.label :enseres %>
        <%= f.collection_radio_buttons :enseres, [[true, 'Si'], [false, 'No']], :first, :last, :default => true, :checked => true%>
      </div>
      <div class="col-md-3 <%='has-error' if @beneficiario.errors.keys.include?(:obs_enseres) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:obs_enseres) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :obs_enseres %>
      </div>
      <div class="col-md-1">
        <%= f.label :discapacidad %>
        <%= f.collection_radio_buttons :discapacidad, [[true, 'Si'], [false, 'No']], :first, :last, :default => true, :checked => false%>
      </div>
      <div class="col-md-3 <%='has-error' if @beneficiario.errors.keys.include?(:obs_discapacidad) ==true %> <%='has-success' if (@beneficiario.errors.keys.include?(:obs_discapacidad) ==false and @beneficiario.errors.any?)%>">
        <%= f.input :obs_discapacidad %>
      </div>
      <div class="col-md-4">
        <%= f.simple_fields_for :historial do |p| %>
        <%= p.label :parentesco %>
        <%= p.select(:parentesco, options_for_select($dic["parentesco"]),{include_blank: 'Seleccione el parentesco...'},class: "form-control" )  %>
        <% end %>
      </div>

  </div>
</li>
</ul>
<%if @beneficiario.cedula.blank?%>
<%= render 'layouts/botones', :f=>f, path: solicitante_path(@solicitante)%>
<%else%>
<%= render 'layouts/botones', :f=>f, path: solicitante_beneficiario_path(@solicitante)%>
<%end%>
  <% end %>

  <script>
  function getParameterByName( name ) //courtesy Artem
  {
      name = name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
      var regexS = "[\\?&]"+name+"=([^&#]*)";
      var regex = new RegExp( regexS );
      var results = regex.exec( window.location.href );
      if( results == null )
        return "";
      else
      {
        if ((results[1].indexOf('?'))>0)
          return decodeURIComponent(results[1].substring(0,results[1].indexOf('?')).replace(/\+/g, " "));
        else
          return decodeURIComponent(results[1].replace(/\+/g, " "));
      }
  }

      var t = getParameterByName('T');
      var c = getParameterByName('C');
      var n = getParameterByName('N');
      var a = getParameterByName('A');
      var s = getParameterByName('S');
      var f = getParameterByName('F');

      document.getElementById("tipo_cedula").value = t;
      document.getElementById("tipo_cedula").disabled = false;

      document.getElementById("cedula").value = c;
      document.getElementById("cedula").disabled = false;

      document.getElementById("nombre").value = n;
      document.getElementById("nombre").disabled = false;

      document.getElementById("apellido").value = a;
      document.getElementById("apellido").disabled = false;

      document.getElementById("sexo").value = s;
      document.getElementById("sexo").disabled = false;

      document.getElementById("fecha").value = f;
      document.getElementById("fecha").disabled = false;

  </script>

app/views/beneficiarios/edit.html.erb
<h1><i class="fa fa-user" style="font-size:50px;"> </i> Editar Beneficiario</h1>

<%= render 'form', beneficiario: @beneficiario %>

app/views/beneficiarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beneficiarios</h1>

<table>
  <thead>
    <tr>
      <th>Tipo cedula</th>
      <th>Cedula</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Sexo</th>
      <th>Fecha de nacimiento</th>
      <th>Oficio</th>
      <th>Estado civil</th>
      <th>Tipo de casa</th>
      <th>Num habitaciones</th>
      <th>Num banos</th>
      <th>Enseres</th>
      <th>Obs enseres</th>
      <th>Discapacidad</th>
      <th>Obs discapacidad</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beneficiarios.each do |beneficiario| %>
      <tr>
        <td><%= beneficiario.tipo_cedula %></td>
        <td><%= beneficiario.cedula %></td>
        <td><%= beneficiario.nombres %></td>
        <td><%= beneficiario.apellidos %></td>
        <td><%= beneficiario.sexo %></td>
        <td><%= beneficiario.fecha_de_nacimiento %></td>
        <td><%= beneficiario.oficio %></td>
        <td><%= beneficiario.estado_civil %></td>
        <td><%= beneficiario.tipo_de_casa %></td>
        <td><%= beneficiario.num_habitaciones %></td>
        <td><%= beneficiario.num_banos %></td>
        <td><%= beneficiario.enseres %></td>
        <td><%= beneficiario.obs_enseres %></td>
        <td><%= beneficiario.discapacidad %></td>
        <td><%= beneficiario.obs_discapacidad %></td>
        <td><%= link_to 'Show', solicitante_beneficiarios_path(beneficiario, beneficiario) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/beneficiarios/new.html.erb
<h1 class="page-header"><i class="fa fa-user" style="font-size:50px;"> </i> Nuevo Beneficiario</h1>

<%= render 'form', beneficiario: @beneficiario %>

app/views/beneficiarios/show.html.erb
<%solicitante= Solicitante.find(params[:solicitante_id])%>
<div class="col-md-12 page-header">
  <div class="col-sm-10">
    <h2><i class="fa fa-user" style="font-size:50px"></i><%= (+ "  " + @beneficiario.nombres + " " + @beneficiario.apellidos).upcase%></h2>
  </div>

</div>
<br>
  <div class="col-md-12">
    <ul class="nav nav-pills nav-justified">
      <li role="presentation"><%=link_to raw('<i class="fa fa-arrow-circle-left"></i> Regresar'), solicitante_path(@solicitante)%></li>
      <li role="presentation" id="edit"><%=link_to raw('<i class="fa fa-pencil"></i> Editar'), edit_solicitante_beneficiario_path(@solicitante, @beneficiario)%></li>
      <li role="presentation"><%=link_to raw('<i class="fa fa-plus"></i> Nueva solicitud'), new_solicitante_beneficiario_solicitud_path(@solicitante, @beneficiario)%></li>
    </ul>
  </div>

<p class="col-md-12">
  <br>
</p>
<div class="col-md-6">
  <ul class="list-group">

    <li class="list-group-item text-muted" contenteditable="false">
      <i class="fa fa-user"></i> Perfil</li>

    <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Cédula</strong>
      </span>
      <td><%= $dic["tipo_de_cedula"].key(@beneficiario.tipo_cedula).to_s + "-" + @beneficiario.cedula.to_s %></td>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Sexo</strong>
     </span>
     <%= $dic["sexo"].key(@beneficiario.sexo).to_s %>
   </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Fecha de Nacimiento</strong>
     </span>
     <%= @beneficiario.fecha_de_nacimiento.strftime("%d-%m-%Y")%>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Estado Civil</strong>
     </span>
     <%= $dic["estado"].key(@beneficiario.estado_civil).to_s%>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Profesion/Oficio</strong>
     </span>
     <%= $dic["oficio"].key(@beneficiario.oficio)%>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Tipo de Casa</strong>
     </span>
     <%= $dic["tipo_de_casa"].key(@beneficiario.tipo_de_casa)%>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Nº de Habitaciones</strong>
     </span>
     <%= @beneficiario.num_habitaciones.to_s%>
     </br>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Nº de Baños</strong>
     </span>
     <%= @beneficiario.num_banos.to_s%>
    </br>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Enseres</strong>
     </span>
    <%= $dic["condicion"].key(@beneficiario.enseres)%>
   </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Observacion</strong>
     </span>
     <%= @beneficiario.obs_enseres.to_s%>
     </br>
    </li>


    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Discapacidad</strong>
     </span>
     <%= $dic["condicion"].key(@beneficiario.discapacidad)%>
    </li>

    <li class="list-group-item text-right">
     <span class="pull-left">
       <strong class="">Observacion</strong>
     </span>
     <%= @beneficiario.obs_discapacidad.to_s%>
   </br>
    </li>

  <ul>
</div>

<% if @solicitudes.length>0 %>
<div class="col-md-6">
<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false"><i class="fa fa-users"></i> Solicitud (es)</li>
  <li class="list-group-item">
    <table class="table table-hover table-condensed text-center">
      <thead>
        <tr>
          <th class="actions text-center">Ayuda</th>
          <th class="actions text-center">Descripción</th>
          <th class="actions text-center">Estatus</th>
          <th class="actions text-center" style="width:17%;">Fecha</th>
        </tr>
      </thead>

      <tbody>
        <% @solicitudes.each do |solicitud|%>
        <tr class="<%=$dic['table_color'].key(solicitud.status)%>">
          <td><%=solicitud.ayuda.nombre%></td>
          <td><%=solicitud.descripcion%></td>
          <td><%=$dic["status"].key(solicitud.status)%></td>
          <td><%=solicitud.created_at.strftime("%d-%m-%Y")%></td>
        </tr>
        <%end%>
      </tbody>

    </table>
  </li>
</ul>
</div>
<%else%>
<div class="text-center col-md-6">
<ul class="list-group">
  <li class="list-group-item text-muted text-left" contenteditable="false">
    <i class="fa fa-comment-o"></i>
    Mensaje</li>
  <li class="list-group-item"></br>
  <i class="fa fa-user-times fa-4x" style="color:#24A5FF;"></i>
  <h2>El beneficiario no tiene solicitudes.</h2>
</li>
</ul>
</div>
<%end%>
</div>

<script type="text/javascript">
$('#edit').click(function () {
  var t = "<%= @beneficiario.tipo_cedula %>";
  var c = "<%= @beneficiario.cedula %>";
  var n = "<%= @beneficiario.nombres %>";
  var a = "<%= @beneficiario.apellidos %>";
  var s = "<%= @beneficiario.sexo %>";
  var f = "<%= @beneficiario.fecha_de_nacimiento %>";

   location.href ="http://localhost:3000/solicitantes/" + "<%= solicitante.id %>" + "/beneficiarios/"+"<%=@beneficiario.id%>"+"/edit?T="+t+"&C="+c+"&N="+n+"&A="+a+"&S="+s+"&F="+f+"";

});

</script>