config/routes.rb
Rails.application.routes.draw do

  resources :solicitantes do
    resources :beneficiarios do
      resources :solicitudes
    end
  end
  resources :solicitudes
  resources :ayudas
  resources :departamentos
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ayuda.rb
class Ayuda < ApplicationRecord
  belongs_to :departamento
  has_many :solicitudes, dependent: :destroy
  validates :nombre, presence: true
  validates :departamento_id, presence: true
end

app/controllers/ayudas_controller.rb
class AyudasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ayuda, only: [:show, :edit, :update, :destroy]

  # GET /ayudas
  # GET /ayudas.json
  def index
    @ayudas = Ayuda.all
  end

  # GET /ayudas/1
  # GET /ayudas/1.json
  def show
  end

  # GET /ayudas/new
  def new
    authorize! :new, Ayuda
    @ayuda = Ayuda.new
  end

  # GET /ayudas/1/edit
  def edit
    authorize! :edit, Ayuda
  end

  # POST /ayudas
  # POST /ayudas.json
  def create
    authorize! :create, Ayuda
    @ayuda = Ayuda.new(ayuda_params)

    respond_to do |format|
      if @ayuda.save
        format.html { redirect_to ayudas_path, notice: 'Ayuda creada exitosamente.' }
        format.json { render :show, status: :created, location: @ayuda }
      else
        format.html { render :new }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudas/1
  # PATCH/PUT /ayudas/1.json
  def update
    authorize! :update, Ayuda
    respond_to do |format|
      if @ayuda.update(ayuda_params)
        format.html { redirect_to ayudas_path, notice: 'Ayuda actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @ayuda }
      else
        format.html { render :edit }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudas/1
  # DELETE /ayudas/1.json
  def destroy
    authorize! :destroy, Ayuda
    @ayuda.destroy
    respond_to do |format|
      format.html { redirect_to ayudas_url, notice: 'Ayuda eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayuda
      @ayuda = Ayuda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayuda_params
      params.require(:ayuda).permit(:nombre, :departamento_id)
    end
end

app/helpers/ayudas_helper.rb
module AyudasHelper
end

app/views/ayudas/_form.html.erb
<%= simple_form_for(ayuda) do |f| %>


<%= f.error_notification %>
<ul class="list-group ">
      <li class="list-group-item text-muted col-md-12" contenteditable="false"><i class="fa fa-database"></i> Datos<div class="pull-right text-warning">
         <i class="fa fa-asterisk"></i> Campo Obligatorio
      </div></li>
      <li class="list-group-item col-md-12">
<div class="form-inputs">

  <div class="col-md-6 <%='has-error' if @ayuda.errors.keys.include?(:nombre) ==true %> <%='has-success' if (@ayuda.errors.keys.include?(:nombre) ==false and @ayuda.errors.any?)%>">
    <%= f.input :nombre, input_html: { class: 'form-control' } %>
  </div>

  <div class="col-md-6 <%='has-error' if @ayuda.errors.keys.include?(:departamento_id) ==true %> <%='has-success' if (@ayuda.errors.keys.include?(:departamento_id) ==false and @ayuda.errors.any?)%>">
      <%= f.association :departamento, :label_method => lambda { |owner| "#{owner.nombre.capitalize}"},  :include_blank => "Seleccione un departamento...", input_html: { class: 'form-control' }  %>
  </div>

</li>
</ul>
  </br>
  <%= render 'layouts/botones', :f=>f, path: ayudas_path%>

</div>
<% end %>

app/views/ayudas/edit.html.erb
<h1 class="page-header"><i class="fa fa-heart" style="font-size:50px;"></i> Editar ayuda</h1>

<%= render 'form', ayuda: @ayuda %>

app/views/ayudas/index.html.erb
<div class="col-md-12 page-header">
  <% if current_user.has_role? :admin %>
  <div class="pull-right">

    <%= link_to raw('<i class="fa fa-plus"></i> Nueva Ayuda'), new_ayuda_path,class:"btn btn-default" %>
  </div>
  <%end%>
  <h1><i class="fa fa-heart" style="font-size:50px;"></i> Ayudas</h1>
</div>

<ul class="list-group">
      <li class="list-group-item text-muted col-md-12" contenteditable="false">Lista de ayudas</li>
      <li class="list-group-item col-md-12">


<table class="table table-responsive table-hover table-condensed text-center " style="font-size:11px;">
  <thead>
    <tr>
      <th class="text-center">Nombre</th>
      <th class="text-center">Departamento</th>
      <% if current_user.has_role? :admin %>
      <th class="text-center">Acciones</th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% if current_user.has_role? :discapacidad %>
      <%dep=1%>
    <% elsif current_user.has_role? :adultos %>
      <%dep=2%>
    <% elsif current_user.has_role? :ninos %>
      <%dep=3%>
    <%end%>

    <% if current_user.has_role? :admin or current_user.has_role? :admon %>
      <% @ayudas.each do |ayuda| %>
      <tr>
        <td class="text-capitalize"><%= ayuda.nombre %></td>
        <td class="text-capitalize"><%= ayuda.departamento.nombre %></td>
        <% if current_user.has_role?:admin %>
        <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_ayuda_path(ayuda),class:"btn1 btn btn-info","data-toggle": "tooltip", "data-placement": "top", title: "Editar elemento" %>
        <%end%>
      <%end%>
      </tr>
    <%end%>

    <%if !current_user.has_role? :admin%>
      <% @ayudas.where(departamento_id: dep).each do |ayuda| %>
      <tr>
        <td class="text-capitalize"><%= ayuda.nombre %></td>
        <td class="text-capitalize"><%= ayuda.departamento.nombre %></td>
        <% if current_user.has_role?:admin %>
          <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_ayuda_path(ayuda),class:"btn1 btn btn-info","data-toggle": "tooltip", "data-placement": "top", title: "Editar elemento" %>
        <%end%>
      <%end%>
      </tr>
    <%end%>

  </tbody>
</table>

<br>

app/views/ayudas/new.html.erb
<h1 class="page-header"><i class="fa fa-heart" style="font-size:50px;"></i> Nueva Ayuda</h1>

<%= render 'form', ayuda: @ayuda %>

app/views/ayudas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ayuda.nombre %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @ayuda.departamento %>
</p>

<%= link_to 'Edit', edit_ayuda_path(@ayuda) %> |
<%= link_to 'Back', ayudas_path %>