config/routes.rb
Rails.application.routes.draw do

  resources :solicitantes do
    resources :beneficiarios do
      resources :solicitudes
    end
  end
  resources :solicitudes
  resources :ayudas
  resources :departamentos
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/solicitante.rb
class Solicitante < ApplicationRecord
  has_many :historiales
  has_many :beneficiarios, through: :historiales
  has_many :solicitudes, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :correo, format: { with: VALID_EMAIL_REGEX, message: 'El formato de correo es inválido'}, :allow_blank => true
  validates :telefono_fijo, :telefono_movil, length: { is: 11 }, allow_blank: true, numericality: { only_integer: true }
  validates :carga_familiar, numericality: { only_integer: true }
  validates :ingreso_mensual, numericality: true
  validates :cedula, :nombres, :apellidos, :tipo_cedula, :estado_civil, :grado_de_instruccion, :municipios, :direccion, :oficio, :carga_familiar, :fecha_de_nacimiento, :lugar_de_nacimiento, :sexo, :ingreso_mensual, presence: true, :allow_blank => false
  validates :cedula, uniqueness: { case_sensitive: false, message: 'Ya se encuentra registrada' }, numericality: { only_integer: true }

  self.per_page = 10
  def self.search(search)
   search = search.downcase

     where('cedula = ?', "#{search}").order(:id)

  end
end

app/controllers/solicitantes_controller.rb
class SolicitantesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_solicitante, only: [:show, :edit, :update, :destroy]

  # GET /solicitantes
  # GET /solicitantes.json
  def index
    if  !params[:search].nil?
    s = params[:search]
      @beneficiarios_b = Beneficiario.search s
      @solicitantes_b = Solicitante.search s
    end
    @solicitantes = Solicitante.all.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
    @beneficiarios = Beneficiario.all.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
    @solicitantes_index = Solicitante.all.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
  end

  # GET /solicitantes/1
  # GET /solicitantes/1.json
  def show
    if  !params[:search].nil?
    s = params[:search]
    @beneficiarios_b = Beneficiario.search s
    end
    @solicitantes_i = params[:solicitante_id]
    @beneficiarios = Beneficiario.all.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
  end

  # GET /solicitantes/new
  def new
    authorize! :new, Solicitante
    @solicitante = Solicitante.new

  end

  # GET /solicitantes/1/edit
  def edit
    authorize! :edit, Solicitante
  end

  # POST /solicitantes
  # POST /solicitantes.json
  def create
    authorize! :create, Solicitante
    @solicitante = Solicitante.new(solicitante_params)

    respond_to do |format|
      if @solicitante.save
        format.html { redirect_to @solicitante, notice: 'Solicitante creado exitosamente.' }
        format.json { render :show, status: :created, location: @solicitante }
      else
        format.html { render :new }
        format.json { render json: @solicitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitantes/1
  # PATCH/PUT /solicitantes/1.json
  def update
    authorize! :update, Solicitante
    respond_to do |format|
      if @solicitante.update(solicitante_params)
        format.html { redirect_to @solicitante, notice: 'Solicitante actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @solicitante }
      else
        format.html { render :edit }
        format.json { render json: @solicitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitantes/1
  # DELETE /solicitantes/1.json
  def destroy
    authorize! :destroy, Solicitante
    @solicitante.destroy
    respond_to do |format|
      format.html { redirect_to solicitantes_url, notice: 'Solicitante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitante
      @solicitante = Solicitante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitante_params
      params.require(:solicitante).permit(:cedula, :tipo_cedula, :nombres, :apellidos, :sexo, :fecha_de_nacimiento, :lugar_de_nacimiento, :direccion, :municipios, :grado_de_instruccion, :obs_instruccion, :oficio, :ingreso_mensual, :obs_ingreso, :empresa, :carga_familiar, :telefono_fijo, :telefono_movil, :estado_civil, :correo)
    end
end

app/helpers/solicitantes_helper.rb
module SolicitantesHelper
end

app/views/solicitantes/_form.html.erb
<%= simple_form_for(@solicitante) do |f| %>


<%= f.error_notification %>
<ul class="list-group ">
  <li class="list-group-item text-muted col-md-12" contenteditable="false"><i class="fa fa-database"></i> Datos<div class="pull-right text-warning">
    <i class="fa fa-asterisk"></i> Campo Obligatorio
      </div></li>
  <li class="list-group-item col-md-12">

    <div class="form-inputs">
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:cedula) ==true or @solicitante.errors.keys.include?(:tipo_de_cedula) ==true %> <%='has-success' if ((@solicitante.errors.keys.include?(:cedula) ==false and @solicitante.errors.keys.include?(:tipo_de_cedula) ==false) and @solicitante.errors.any?)%>">
        <div class="form-group">
          <%= f.label :cedula, class: "control-label"%>
          <div class="input-group form-inline">
            <span class="input-group-btn">
              <%= f.select(:tipo_cedula , options_for_select($dic["tipo_de_cedula"],@solicitante.tipo_cedula),{include_blank: ''}, class: "dropdown-toggle form-control", style: "padding:7px 12px;width:60px" ) %>

            </span>
              <%= f.input_field :cedula, label: false, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:nombres) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:nombres) ==false and @solicitante.errors.any?)%>">
        <%= f.input :nombres %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:apellidos) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:apellidos) ==false and @solicitante.errors.any?)%>">
        <%= f.input :apellidos %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:sexo) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:sexo) ==false and @solicitante.errors.any?)%>">
        <%= f.input :sexo, collection: $dic["sexo"], include_blank: 'Seleccione un sexo...', class: "form-control"  %>
      </div>
      <div class="col-md-2 <%='has-error' if @solicitante.errors.keys.include?(:fecha_de_nacimiento) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:fecha_de_nacimiento) ==false and @solicitante.errors.any?)%>">
        <%= f.input :fecha_de_nacimiento, as: :date, html5: true %>
      </div>
      <div class="col-md-2 <%='has-error' if @solicitante.errors.keys.include?(:lugar_de_nacimiento) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:lugar_de_nacimiento) ==false and @solicitante.errors.any?)%>">
        <%= f.input :lugar_de_nacimiento %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:municipios) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:municipios) ==false and @solicitante.errors.any?)%>">
        <%= f.label :municipios %>
        <%= f.select(:municipios , options_for_select($dic["municipios"],@solicitante.municipios),{include_blank: 'Seleccione un municipio...'},class: "form-control" )  %>
      </div>
      <div class="col-md-8 <%='has-error' if @solicitante.errors.keys.include?(:direccion) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:direccion) ==false and @solicitante.errors.any?)%>">
        <%= f.input :direccion %>
      </div>
      <div class="col-md-2 <%='has-error' if @solicitante.errors.keys.include?(:grado_de_instruccion) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:grado_de_instruccion) ==false and @solicitante.errors.any?)%>">
        <%= f.label :grado_de_instruccion %>
        <%= f.select(:grado_de_instruccion , options_for_select($dic["grado"],@solicitante.municipios),{include_blank: 'Seleccione el grado de instrucción...'},class: "form-control" )  %>
      </div>
      <div class="col-md-2">
        <%= f.input :obs_instruccion %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:estado_civil) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:estado_civil) ==false and @solicitante.errors.any?)%>">
        <%= f.label :Estado_civil %>
        <%= f.select(:estado_civil , options_for_select($dic["estado"],@solicitante.municipios),{include_blank: 'Seleccione el estado civil...'},class: "form-control" )  %>
      </div>
      <div class="col-md-4">
        <%= f.input :correo %>
      </div>
      <div class="col-md-4">
        <%= f.input :telefono_fijo %>
      </div>
      <div class="col-md-4">
        <%= f.input :telefono_movil %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:oficio) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:oficio) ==false and @solicitante.errors.any?)%>">
        <%= f.label :oficio %>
        <%= f.select(:oficio , options_for_select($dic["oficio"],@solicitante.oficio),{include_blank: 'Seleccione un oficio...'},class: "form-control" )  %>
      </div>
      <div class="col-md-4">
        <%= f.input :empresa %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:ingreso_mensual) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:ingreso_mensual) ==false and @solicitante.errors.any?)%>">
        <%= f.input :ingreso_mensual %>
      </div>
      <div class="col-md-4">
        <%= f.input :obs_ingreso %>
      </div>
      <div class="col-md-4 <%='has-error' if @solicitante.errors.keys.include?(:carga_familiar) ==true %> <%='has-success' if (@solicitante.errors.keys.include?(:carga_familiar) ==false and @solicitante.errors.any?)%>">
        <%= f.input :carga_familiar %>
      </div>
    </div>
   </li>
  </ul>

  <%if @solicitante.cedula.blank?%>
  <%= render 'layouts/botones', :f=>f, path: solicitantes_path%>
  <%else%>
  <%= render 'layouts/botones', :f=>f, path: solicitante_path(@solicitante)%>
  <%end%>
<% end %>

app/views/solicitantes/_resultado.html.erb
<br>
<%
p=@solicitantes_b
if p.length>0%>
<div class="table-responsive">

    <table class="table table-responsive table-hover table-condensed" style="font-size:11px;">
        <thead>
            <tr>
                <th class="text-center">Cédula</th>
                <th class="text-center">Nombre Completo</th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>

        <tbody>
            <% @solicitantes_b.each do |solicitante| %>
            <tr class="text-center">
                <td><%= $dic["tipo_de_cedula"].key(solicitante.tipo_cedula).to_s + "-" + solicitante.cedula.to_s %></td>
                <td class="text-capitalize text-center"><%= solicitante.nombres.downcase + " " +solicitante.apellidos.downcase %></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
                        <%= link_to raw('<i class="fa fa-eye"></i>'), solicitante,class:"btn btn-success","data-toggle": "tooltip", "data-placement": "top", title: "Ver solicitante" %>
                        <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_solicitante_path(solicitante),class:"btn btn-info","data-toggle": "tooltip", "data-placement": "top", title: "Editar solicitante" %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<%else%>
<div class="text-center">
    <h4>"No hay personas con esta cédula."</h4>
    <a href="<%= new_solicitante_path+"?cedula="+params[:search]%>" class="btn btn-default">Agregar solicitante</a>
</div>
<%end%>

app/views/solicitantes/_resultado2.html.erb
<br>
<%
d = @solicitantes_i
r=@beneficiarios_b
if r.length>0%>
<div class="table-responsive">

    <table class="table table-responsive table-hover table-condensed" style="font-size:11px;">
        <thead>
            <tr>
                <th class="text-center">Cédula</th>
                <th class="text-center">Nombre Completo</th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>

        <tbody>
                  <% @beneficiarios_b.each do |beneficiario| %>
                  <tr class="text-center">
                      <td><%= $dic["tipo_de_cedula"].key(beneficiario.tipo_cedula).to_s + "-" + beneficiario.cedula.to_s %></td>
                      <td class="text-capitalize text-center"><%= beneficiario.nombres.downcase + " " +beneficiario.apellidos.downcase %></td>
                      <td class="text-center">
                        <%= d %>
                      </td>
                  </tr>
                  <% end %>
        </tbody>
    </table>
</div>
<%else%>
<div class="text-center">
    <h4>"No hay personas con esta cédula."</h4>
    <!--<a href="<%= new_solicitante_beneficiario_path(:solicitante_id)%>" class="btn btn-default">Agregar beneficiario</a>-->
</div>
<%end%>

app/views/solicitantes/_solicitantes.html.erb
<ul class="list-group">
      <li class="list-group-item text-muted" contenteditable="false">Búsqueda</li>
      <li class="list-group-item ">

        <div class="input-group">


          <input type="text" class="form-control" placeholder="Ingrese cédula" name="search" id="search" value="<%= params[:search]%>">


          <span class="input-group-addon">
            <span id="search_icon" class="fa fa-search"></span>

          </span>
        </div>
      </li>
    </ul>
    <ul class="list-group">
          <li class="list-group-item text-muted" contenteditable="false"><i class="fa fa-wpforms"></i> Resultado</li>
          <li class="list-group-item ">
            <div class="resultado">
                <h2 class="text-center"><small>Realice una búsqueda...</small></h2>
            </div>
          </li>
        </ul>

app/views/solicitantes/edit.html.erb
<h1 class="page-header"><i class="fa fa-user" style="font-size:50px;"></i> Editar Solicitante</h1>

<%= render 'form', solicitante: @solicitante %>

app/views/solicitantes/new.html.erb
<h1 class="page-header"><i class="fa fa-user" style="font-size:50px;"></i> Nuevo Solicitante</h1>

<%= render 'form', solicitante: solicitantes_path %>

app/views/solicitantes/show.html.erb
<div class="col-md-12 page-header">
  <div class="col-sm-10">
    <h2><i class="fa fa-user" style="font-size:50px;"></i><%= (+ "  " + @solicitante.nombres + " " + @solicitante.apellidos).upcase%></h2>
  </div>

</div>
<br>
  <div class="col-md-12">
    <ul class="nav nav-pills nav-justified">
      <li role="presentation"><%=link_to raw('<i class="fa fa-arrow-circle-left"></i> Regresar'), solicitantes_path%></li>
      <li role="presentation"><%=link_to raw('<i class="fa fa-pencil"></i> Editar'), edit_solicitante_path(@solicitante)%></li>
      <li style="padding-left:90px; color:#666" role="presentation" type="button" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Nuevo Beneficiario</li>
      <!--<%=link_to raw('<i class="fa fa-plus"></i> Nuevo Beneficiario'), new_solicitante_beneficiario_path(@solicitante)%> -->
    </ul>
  </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" style="margin-top:150px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">
              <i class="fa fa-user fa-2x"></i>
              Nuevo Beneficiario</h4>
          </div>
          <div class="modal-body">
            <div class="col-xs-12 form-group" style="float:none">
            <div class="text-capitalize"><%= label_tag "¿Solicitante es el mismo beneficiario? " %>

            </br>
            <input type="radio" id="si" name="son_el_mismo" value="Si" class="son_el_mismo"/>
              <%= label_tag "Si" %>
            </br>
              <input type="radio" id="no" name="son_el_mismo" value="No" checked="checked" class="son_el_mismo"/>
              <%= label_tag "No" %>
            </br>
            </div>


            <div class="form-group input-group contenido">
              <!--Inicio del contenido del modal -->
              <div class="row">
                    <div class="col-md-12">
                      <ul class="list-group">
                        <li class="list-group-item text-muted" contenteditable="false">Búsqueda</li>
                        <li class="list-group-item ">

                          <div class="input-group">

                            <input type="text" class="form-control" placeholder="Buscar por cédula" name="search" id="search" value="<%= params[:search]%>">

                            <span class="input-group-addon">
                              <span id="search_icon" class="fa fa-search"></span>

                            </span>
                          </div>
                        </li>
                      </ul>
                      <ul class="list-group" style="width:500px">
                            <li class="list-group-item text-muted" contenteditable="false"><i class="fa fa-wpforms"></i> Resultado</li>
                            <li class="list-group-item ">
                              <div class="resultado2" id="resultado2">
                                <h2 class="text-center"><small>Realice una búsqueda...</small></h2>
                              </div>
                            </li>
                      </ul>
                      </div>
                </div>
              <!--Fin del contenido del modal -->
            </div>
          </div>
          </div>
              <div class="modal-footer">
                <div class="btn-group btn-group-md form-inline" role="group" aria-label="...">
                    <button type="button" class="btn btn-primary" id="generar_boton" name="button">Agregar</button>
                </div>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
              </div>
        </div>
      </div>
  </div>
  <!-- Fin Modal -->

<p class="col-md-12">
  <br>
</p>
<div class="col-md-6">
  <ul class="list-group">
    <li class="list-group-item text-muted" contenteditable="false">
      <i class="fa fa-user"></i> Perfil</li>

    <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Cédula</strong>
      </span>
      <td><%= $dic["tipo_de_cedula"].key(@solicitante.tipo_cedula).to_s + "-" + @solicitante.cedula.to_s %></td>
    </li>


     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Estado Civil</strong>
      </span>
      <%= $dic["estado"].key(@solicitante.estado_civil).to_s %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Sexo</strong>
      </span>
      <%= $dic["sexo"].key(@solicitante.sexo).to_s %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Fecha de Nacimiento</strong>
      </span>
      <%= @solicitante.fecha_de_nacimiento.strftime("%d-%m-%Y")%>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Lugar de Nacimiento</strong>
      </span>
      <%= @solicitante.lugar_de_nacimiento.capitalize %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Dirección</strong>
      </span>
      <%= @solicitante.direccion.capitalize %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Municipio</strong>
      </span>
      <%= $dic["municipios"].key(@solicitante.municipios).to_s %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Grado de Instrucción</strong>
      </span>
      <%= $dic["grado"].key(@solicitante.grado_de_instruccion).to_s %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Observación</strong>
      </span>
      <%= @solicitante.obs_instruccion.capitalize %>
      <br>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Profesión/Oficio</strong>
      </span>
      <%= @solicitante.oficio %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Ingreso Mensual</strong>
      </span>

      <%= number_to_currency(@solicitante.ingreso_mensual, unit: "", separator: ",", delimiter: ".", format: "%n %u") %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Observación</strong>
      </span>
      <%= @solicitante.obs_ingreso.capitalize %>
      <br>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Empresa</strong>
      </span>
      <%= @solicitante.empresa.capitalize %>
    </br>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Carga Familiar</strong>
      </span>
      <%= @solicitante.carga_familiar.to_s %>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Teléfono Fijo</strong>
      </span>
      <%= @solicitante.telefono_fijo %>
      <br>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Teléfono Móvil</strong>
      </span>
      <%= @solicitante.telefono_movil %>
      <br>
     </li>

     <li class="list-group-item text-right">
      <span class="pull-left">
        <strong class="">Correo Electrónico</strong>
      </span>
      <%= @solicitante.correo %>
      <br>
     </li>
   </ul>
</div>
   <% if @solicitante.beneficiarios.length>0 %>
   <div class="col-md-6">
   <ul class="list-group">
     <li class="list-group-item text-muted" contenteditable="false"><i class="fa fa-users"></i> Beneficiario (os)</li>
     <li class="list-group-item">
       <table class="table table-hover table-condensed text-center">
         <thead>
           <tr>
             <th class="actions text-center" style="width:18%;">Cédula</th>
             <th class="actions text-center">Nombres</th>
             <th class="actions text-center" style="width:17%;">Fecha de Nacimiento</th>
             <th class="actions text-center" style="width:10%;">Sexo</th>
             <th class="actions text-center" style="width:10%;">Acciones</th>
           </tr>
         </thead>

         <tbody>
           <%@solicitante.beneficiarios.each do |beneficiario|%>
           <tr>
             <%if beneficiario.cedula == @solicitante.cedula%>
             <%else%>
             <td><%="#{$dic['tipo_de_cedula'].key(beneficiario.tipo_cedula)}-#{beneficiario.cedula}"%></td>
             <td class="text-capitalize"><%="#{beneficiario.nombres} #{beneficiario.apellidos}"%></td>
             <td><%=beneficiario.fecha_de_nacimiento.strftime("%d-%m-%Y")%></td>
             <td><%=$dic["sexo"].key(beneficiario.sexo.to_i)%></td>
             <td><%= link_to raw('<i class="fa fa-eye"></i>'), solicitante_beneficiario_path(@solicitante, beneficiario),class:"btn1 btn btn-success" %></td>
           </tr>
           <%end%>
           <%end%>
         </tbody>

       </table>
     </li>
   </ul>
   </div>
   <%else%>
   <div class="text-center col-md-6">
   <ul class="list-group">
     <li class="list-group-item text-muted text-left" contenteditable="false">
       <i class="fa fa-comment-o"></i>
       Mensaje</li>
     <li class="list-group-item"></br>
     <i class="fa fa-user-times fa-4x" style="color:#24A5FF;"></i>
     <h2>El solicitante no tiene beneficiarios.</h2>
   </li>
   </ul>
   </div>
   <%end%>

<!-- Solicitudes -->
<% if @solicitante.beneficiarios.length>0 %>
<div class="col-md-6">
<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false"><i class="fa fa-users"></i>Mis Solicitudes</li>
  <li class="list-group-item">
    <table class="table table-hover table-condensed text-center">
      <thead>
      </thead>

      <tbody>
        <%@solicitante.beneficiarios.each do |beneficiario|%>
        <tr>
          <%if beneficiario.cedula != @solicitante.cedula%>

          <%else%>
            <td class="text-capitalize"><%="Ver Mis Solicitudes"%></td>
            <td><%= link_to raw('<i class="fa fa-eye"></i>'), solicitante_beneficiario_path(@solicitante, beneficiario),class:"btn1 btn btn-success" %></td>
        </tr>
        <%end%>
        <%end%>
      </tbody>

    </table>
  </li>
</ul>
</div>
<%else%>
<div class="text-center col-md-6">
<ul class="list-group">
  <li class="list-group-item text-muted text-left" contenteditable="false">
    <i class="fa fa-comment-o"></i>
    Mensaje</li>
  <li class="list-group-item"></br>
  <i class="fa fa-paper-plane fa-4x" style="color:#24A5FF;"></i>
  <h2>El solicitante no tiene solicitudes.</h2>
</li>
</ul>
</div>
<%end%>

</div>

<script type="text/javascript">
//Bloque del buscador
    var classes = ".resultado2";
    var delay = (function () {
      var timer = 0;
      return function (callback, ms) {
        clearTimeout(timer);
        timer = setTimeout(callback, ms);
      };
    })();
    function loading() {
      $("#search_icon").attr("class", "fa fa-refresh fa-spin fa-fw")
    }
    function query() {
      loading();
      return "/solicitantes?search=" + $("#search").val();
    }
    $(function () {

      $("#search").keyup(function () {
        delay(function () {
          $.getScript(query());
          return false;
        }, 500);
      });

    });
//Bloque del buscador



  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });

  $('#generar_boton').click(function () {
    var si = document.getElementById("si");
    var no = document.getElementById("no");
    var t = "<%= @solicitante.tipo_cedula %>";
    var c = "<%= @solicitante.cedula %>";
    var n = "<%= @solicitante.nombres %>";
    var a = "<%= @solicitante.apellidos %>";
    var s = "<%= @solicitante.sexo %>";
    var f = "<%= @solicitante.fecha_de_nacimiento %>";

    if(si.checked){
     location.href ="http://localhost:3000/solicitantes/" + "<%= @solicitante.id %>" + "/beneficiarios/new?T="+t+"&C="+c+"&N="+n+"&A="+a+"&S="+s+"&F="+f+"";
    }else{
     location.href = "http://localhost:3000/solicitantes/" + "<%= @solicitante.id %>" + "/beneficiarios/new";
   };
  });

  //function s(x,y) {
  //$('#enviar').modal({
    //show: true, backdrop:false
  //});

  //Bloque de ocultar
  $(document).ready(function(){
        $(".son_el_mismo").click(function(evento){

            var valor = $(this).val();

            if(valor == 'Si'){
                $(".contenido").css("display", "none");
            }else{
                $(".contenido").css("display", "block");
            }
        });
  });
</script>