config/routes.rb
Rails.application.routes.draw do

  resources :solicitantes do
    resources :beneficiarios do
      resources :solicitudes
    end
  end
  resources :solicitudes
  resources :ayudas
  resources :departamentos
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
       can :manage, :all
    elsif user.has_role? :discapacidad
       alias_action :create, update: :cu
       alias_action :new, :create, :edit, update: :ceu
       can :manage, Solicitante
       can :manage, Beneficiario
       can :manage, Solicitud
       cannot :cu, Departamento
       cannot :cu, Ayuda
    elsif user.has_role? :ninos
      can :manage, Solicitante
      can :manage, Beneficiario
      can :manage, Solicitud
      cannot :cu, Departamento
      cannot :cu, Ayuda
    elsif user.has_role? :adultos
      can :manage, Solicitante
      can :manage, Beneficiario
      can :manage, Solicitud
      cannot :cu, Departamento
      cannot :cu, Ayuda
    elsif user.has_role? :admon
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the users
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ayuda.rb
class Ayuda < ApplicationRecord
  belongs_to :departamento
  has_many :solicitudes, dependent: :destroy
  validates :nombre, presence: true
  validates :departamento_id, presence: true
end

app/models/beneficiario.rb
class Beneficiario < ApplicationRecord
  has_many :historiales
  has_many :solicitantes, through: :historiales
  has_many :solicitudes, dependent: :destroy

  accepts_nested_attributes_for :historiales

  validates :cedula, :nombres, :apellidos, :tipo_cedula, :sexo, :fecha_de_nacimiento, :oficio, :estado_civil, :tipo_de_casa, :num_habitaciones, :num_banos, presence: true, :allow_blank => false
  validates :cedula, uniqueness: { case_sensitive: false, message: 'Ya se encuentra registrada' }, numericality: { only_integer: true }

  def self.search(search)
     search = search.downcase

      where('cedula = ?', "#{search}").order(:id)

  end
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  resourcify
  validates :nombre, presence: true, uniqueness: { case_sensitive: false }
  has_many :ayudas ,  dependent: :destroy
end

app/models/historial.rb
class Historial < ApplicationRecord
  belongs_to :solicitante
  belongs_to :beneficiario 
end

app/models/relacion.rb
class Relacion < ApplicationRecord
  belongs_to :solicitante
  belongs_to :beneficiario
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/solicitante.rb
class Solicitante < ApplicationRecord
  has_many :historiales
  has_many :beneficiarios, through: :historiales
  has_many :solicitudes, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :correo, format: { with: VALID_EMAIL_REGEX, message: 'El formato de correo es inválido'}, :allow_blank => true
  validates :telefono_fijo, :telefono_movil, length: { is: 11 }, allow_blank: true, numericality: { only_integer: true }
  validates :carga_familiar, numericality: { only_integer: true }
  validates :ingreso_mensual, numericality: true
  validates :cedula, :nombres, :apellidos, :tipo_cedula, :estado_civil, :grado_de_instruccion, :municipios, :direccion, :oficio, :carga_familiar, :fecha_de_nacimiento, :lugar_de_nacimiento, :sexo, :ingreso_mensual, presence: true, :allow_blank => false
  validates :cedula, uniqueness: { case_sensitive: false, message: 'Ya se encuentra registrada' }, numericality: { only_integer: true }

  self.per_page = 10
  def self.search(search)
   search = search.downcase

     where('cedula = ?', "#{search}").order(:id)

  end
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
  belongs_to :ayuda
  belongs_to :beneficiario
  belongs_to :solicitante
  validates :status, :ayuda, presence: true
  self.per_page = 10

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

      def self.current
        Thread.current[:user]
      end
      def self.current=(user)
             Thread.current[:user] = user.id
      end
end

app/controllers/ayudas_controller.rb
class AyudasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ayuda, only: [:show, :edit, :update, :destroy]

  # GET /ayudas
  # GET /ayudas.json
  def index
    @ayudas = Ayuda.all
  end

  # GET /ayudas/1
  # GET /ayudas/1.json
  def show
  end

  # GET /ayudas/new
  def new
    authorize! :new, Ayuda
    @ayuda = Ayuda.new
  end

  # GET /ayudas/1/edit
  def edit
    authorize! :edit, Ayuda
  end

  # POST /ayudas
  # POST /ayudas.json
  def create
    authorize! :create, Ayuda
    @ayuda = Ayuda.new(ayuda_params)

    respond_to do |format|
      if @ayuda.save
        format.html { redirect_to ayudas_path, notice: 'Ayuda creada exitosamente.' }
        format.json { render :show, status: :created, location: @ayuda }
      else
        format.html { render :new }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudas/1
  # PATCH/PUT /ayudas/1.json
  def update
    authorize! :update, Ayuda
    respond_to do |format|
      if @ayuda.update(ayuda_params)
        format.html { redirect_to ayudas_path, notice: 'Ayuda actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @ayuda }
      else
        format.html { render :edit }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudas/1
  # DELETE /ayudas/1.json
  def destroy
    authorize! :destroy, Ayuda
    @ayuda.destroy
    respond_to do |format|
      format.html { redirect_to ayudas_url, notice: 'Ayuda eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayuda
      @ayuda = Ayuda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayuda_params
      params.require(:ayuda).permit(:nombre, :departamento_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  ##Buscador de solicitantes --Begin
    if  !params[:search].nil?
    s = params[:search]
      @solicitantes_b = Solicitante.search s
    end
    @solicitantes = Solicitante.all.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
  end
  ## --end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayudas_helper.rb
module AyudasHelper
end

app/helpers/beneficiarios_helper.rb
module BeneficiariosHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/solicitantes_helper.rb
module SolicitantesHelper
end

app/helpers/solicitudes_helper.rb
module SolicitudesHelper
end

app/views/layouts/_botones.html.erb
<div class="col-md-12">
</br>
</div>
  <ul class="list-group">
        <li class="list-group-item text-muted col-md-12" contenteditable="false"><i class="fa fa-bars"></i> Acciones<div class="pull-right text-warning">
           <i class="fa fa-warning"></i> Revise los datos antes de guardar
        </div></li>
        <li class="list-group-item col-md-12 text-center">

            <button type="submit" name="button" class="btn btn-primary">
              <%= raw('<i class="fa fa-save"></i> Guardar') %>
            </button>
            <%= link_to raw('<i class="fa fa-arrow-left"></i> Regresar'), path,class:"btn btn-default" %>
            </br>
        </li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ayudas Sociales - FUNSONE</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body>
    <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= image_tag "logo.png", class: "navbar-brand"%>
                    <a class="navbar-brand" href="<%= home_index_path%>">Ayudas Sociales</a>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <li>

                        <i class="fa fa-calendar"></i>
                        <%=Time.now.strftime("%d-%m-%Y")%></i>

                    <!-- /.dropdown-user -->
                </li>
                <%if user_signed_in?%>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">

                        <li>
                            <%= link_to raw("<i class=\"fa fa-sign-out fa-lg\"></i> Cerrar Sesión"), destroy_user_session_path,method: :delete%>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <%end%>
                <!-- /.dropdown -->
            </ul>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <%if user_signed_in?%>
                        <li>
                            <a href="<%= home_index_path%>">
                                <i class="fa fa-home fa-fw fa-2x"></i>
                                Inicio</a>
                        </li>
                        <% if current_user.has_role?:admin %>
                        <li>
                            <a href="<%= departamentos_path%>">
                                <i class="fa fa-building fa-fw fa-2x"></i>
                                Departamentos</a>
                        </li>
                        <%end%>
                        <li>
                            <a href="<%= ayudas_path%>">
                                <i class="fa fa-heart fa-fw fa-2x"></i>
                                Ayudas</a>
                        </li>
                        <li>
                            <a href="<%= solicitantes_path%>">
                                <i class="fa fa-users fa-fw fa-2x"></i>
                                Solicitantes</a>
                        </li>
                        <li>
                            <a href="<%= solicitudes_path%>">
                                <i class="fa fa-paper-plane fa-fw fa-2x"></i>
                                Solicitudes</a>
                        </li>
                        <li>
                          <a data-toggle="modal" data-target="#myModal"><i class="fa fa-file-pdf-o fa-fw fa-2x"></i>  Reportes</a>
                        </li>
                        <li>
                            <small>Coordinación de Informática y sistemas (2017)</small>
                        </li>

                    </ul>
                    <%else%>
                    <li class="text-center">
                        <%= link_to raw("<i class=\"fa fa-sign-in fa-5x\"></i>"), new_user_session_path%>
                    </li>

                    <li class="text-center">
                        <a href="#">INICIE SESIÓN PARA ACCEDER AL SISTEMA.</a>

                    </li>
                    <li>
                        <small>Coordinación de Informática y sistemas (2017)</small>
                    </li>
                    <%end%>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
        </nav>
        <div id="page-wrapper">

            <div class="row">
                <%if !notice.nil?%>
            </br>
            <p class="alert alert-success fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <%= notice %></p>
            <%end%>
            <%= yield %>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" style="margin-top:60px; margin-left:100px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <i class="fa fa-file-pdf-o fa-2x"></i>
          Generador de Reportes</h4>
      </div>
      <div class="modal-body">
        <div class="col-xs-12 form-group" style="float:none">

        <div class="form-group input-group">
          <!--Inicio del contenido del modal -->
          <div class="col-xs-12 form-group">
            <%= label_tag "Fecha Inicio".capitalize %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-calendar fa-fw"></span>
              </span>
              <input class="form-control" type="date" id="fecha_i">
            </div>
          </div>

          <div class="col-xs-12 form-group">
            <%= label_tag "Fecha Fin".capitalize %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-calendar fa-fw"></span>
              </span>
              <input class="form-control" type="date" id="fecha_f">
            </div>
          </div>

          <div class="col-xs-12 form-group">
              <%= label_tag "Departamento" %>
              <div class="form-group input-group">
                <span class="input-group-addon">
                  <span class="fa fa-building fa-fw"></span>
                </span>
                <%= select_tag("Departamento",options_for_select(Departamento.all.map{|d|[d.nombre.capitalize, d.id]}.prepend([t('Ninguno'), 0])),{include_blank:'Todos',class: "form-control" }) %>
              </div>
          </div>

          <div class="col-xs-12 form-group">
              <%= label_tag "Ayuda" %>
              <div class="form-group input-group">
                <span class="input-group-addon">
                  <span class="fa fa-heart fa-fw"></span>
                </span>
                <%= select_tag("Ayuda",options_for_select(Ayuda.all.map{|d|["#{d.nombre.capitalize} - #{d.departamento.nombre}", d.id]}.prepend([t('Ninguna'), 0])),{include_blank:'Todas',class: "form-control" }) %>
              </div>
          </div>

          <div class="col-xs-12 form-group">
              <%= label_tag "Ayuda" %>
              <div class="form-group input-group">
                <span class="input-group-addon">
                  <span class="fa fa-check fa-fw"></span>
                </span>
                <%= select_tag("Estado",options_for_select($dic["status"]),{include_blank:'Seleccione el estado ...',class: "form-control" }) %>
              </div>
          </div>
          <input type="hidden" id="filtro" value="">

          <!--Fin del contenido del modal -->
        </div>
      </div>
      </div>
          <div class="modal-footer">
            <div class="btn-group btn-group-md form-inline" role="group" aria-label="...">
                <button type="button" class="btn btn-primary" id="generar_boton" name="button">Generar</button>
            </div>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
          </div>
    </div>
  </div>
</div>
<!-- Fin Modal -->
  </body>
</html>


<script type="text/javascript">

function s(x,y) {
$('#enviar').modal({
  show: true, backdrop:false
});
  $("#progreso").html("progreso: " + x + "/" + $('.persona'+$("#filtro").attr("value")).length)
  $.ajax({
    statusCode: {
    500: function() {
      $("#progreso").html("¡Error interno!");
      $("#progreso_icon").attr("class","fa fa-ban fa-5x");
    }
  },
    method: "POST",
    url: "/personas/" + $('.persona'+$("#filtro").attr("value"))[x].value + "/enviar?ahora="+y
  }).done(function () {
    x = x + 1
    if (x < $('.persona'+$("#filtro").attr("value")).length) {
      s(x,y);
    } else {
      $("#progreso").html("¡Todos los recibos han sido enviados!");
      $("#progreso_icon").attr("class","fa fa-check fa-5x");
    }
  });
}


function generar(eco) {

  if ($('#Tipo').val() == '') {
    alert('Seleccione una opcion en el campo nómina.');
    return;
  }
  if ($('#tipo_de_reporte').val() == '') {
    alert('Seleccione una opcion en el campo tipo de reporte.');
    return;
  }
  if ($('#Concepto').val() === "0" && $('#Conceptopersonal').val() === "0") {
    alert('Seleccione al menos una clase de concepto.');
    return;
  }
  var concepto = "&c=" + $('#Concepto').val();

  var conceptopersonal = "&cp=" + $('#Conceptopersonal').val();

  var params = '?doc=' + (parseInt($('#tipo_de_reporte').val()) + eco) + conceptopersonal + concepto + '&ahora=' + $('#quincena').val();
  var win = window.open('<%=solicitudes_path%>/' + $('#Tipo').val() + '.pdf' + params, '_blank');
  if (win) {
    //Browser has allowed it to be opened
    win.focus();
  } else {
    //Broswer has blocked it
    alert('Please allow popups for this site');
  }
}

$(function () {

  $('[data-toggle="tooltip"]').tooltip();
  $('#generar_boton').click(function () {
    generar(0);
  });
  $('#generar_boton_eco').click(function () {
    generar(1);
  });
  $('.enviar_recibos_pasada').click(function () {

$('#filtro').attr("value", $(this).attr("value"));
$("#progreso_icon").attr("class","fa fa-refresh fa-spin fa-5x fa-fw margin-bottom");
    s(0,"<%= Time.now%>");
  });
  $('.enviar_recibos').click(function () {
    $('#filtro').attr("value", $(this).attr("value"));

$("#progreso_icon").attr("class","fa fa-refresh fa-spin fa-5x fa-fw margin-bottom");

  });
});
</script>